accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.myAccount),
    path("registerUser/", views.registerUser, name="registerUser"),
    path("registerVendor/", views.registerVendor, name="registerVendor"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("myAccount/", views.myAccount, name="myAccount"),
    path("custDashboard/", views.custDashboard, name="custDashboard"),
    path("vendorDashboard/", views.vendorDashboard, name="vendorDashboard"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path(
        "reset_password_validate/<uidb64>/<token>/",
        views.reset_password_validate,
        name="reset_password_validate",
    ),
    path("reset_password/", views.reset_password, name="reset_password"),
    path("vendor/", include("vendor.urls", namespace="vendor")),
    path("customer/", include("customers.urls", namespace="customer")),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("accounts.urls", namespace="accounts")),
    path("marketplace/", include("marketplace.urls", namespace="market")),
    path("checkout/", MarketplaceViews.checkout, name="checkout"),
    path("order/", include("orders.urls", namespace="order")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home")
    ]

marketplace/urls.py
from django.urls import path
from . import views

app_name = "market"

urlpatterns = [
    path("", views.marketplace, name="marketplace"),
    path("<slug:vendor_slug>/", views.vendor_detail, name="vendor_detail"),
    # Add to Cart
    path("add_to_cart/<int:food_id>/", views.add_to_cart, name="add_to_cart"),
    path("decrease_cart/<int:food_id>/", views.decrease_cart, name="decrease_cart"),
    # show cart Items
    path("show/cart", views.cart, name="cart"),
    path("show/search", views.search, name="search"),
    # DELETE CART ITEM
    path("delete_cart/<int:cart_id>/", views.delete_cart, name="delete_cart"),
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = "order"

urlpatterns = [
    path("place_order/", views.place_order, name="place_order"),
    path("payments/", views.payments, name="payments"),
    path("order_complete/", views.order_complete, name="order_complete"),
]

marketplace/models.py
from django.db import models

from accounts.models import User
from menu.models import FoodItem


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.user


class Tax(models.Model):
    tax_type = models.CharField(max_length=10, unique=True)
    tax_percentage = models.DecimalField(
        decimal_places=2, max_digits=3, verbose_name="Tax Percentage (%)"
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "tax"

    def __str__(self):
        return self.tax_type

marketplace/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from vendor.models import Vendor, OpeningHour
from menu.models import Category, FoodItem
from orders.forms import OrderForm
from django.db.models import Prefetch
from accounts.models import UserProfile
from .models import Cart
from .context_processors import get_cart_counter, get_cart_amounts
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from django.contrib.gis.geos import GEOSGeometry
from django.contrib.gis.measure import D
from django.contrib.gis.db.models.functions import Distance
from datetime import date


# Create your views here.
def marketplace(request):
    vendors = Vendor.objects.filter(is_approved=True, user__is_active=True)
    vendor_count = vendors.count()
    context = {
        "vendors": vendors,
        "vendor_count": vendor_count,
    }
    return render(request, "marketplace/listings.html", context)


def vendor_detail(request, vendor_slug):
    vendor = get_object_or_404(Vendor, vendor_slug=vendor_slug)

    categories = Category.objects.filter(vendor=vendor).prefetch_related(
        # reverse relationship i.e get all fooditems for a category ,category
        # is fk in FoodItem model.
        Prefetch("fooditems", queryset=FoodItem.objects.filter(is_available=True))
    )
    opening_hours = OpeningHour.objects.filter(vendor=vendor).order_by(
        "day", "from_hour"
    )
    # check current days opening hr
    today_date = date.today()
    today = today_date.isoweekday()

    # todays opening hour
    current_opening_hours = OpeningHour.objects.filter(vendor=vendor, day=today)

    print(today_date, today)

    if request.user.is_authenticated:
        cart_items = Cart.objects.filter(user=request.user)
    else:
        cart_items = None

    context = {
        "vendor": vendor,
        "categories": categories,
        "cart_items": cart_items,
        "opening_hours": opening_hours,
        "current_opening_hours": current_opening_hours,
    }

    return render(request, "marketplace/vendor_detail.html", context)


def add_to_cart(request, food_id):
    print(food_id)
    if request.user.is_authenticated:
        if request.headers.get("x-requested-with") == "XMLHttpRequest":
            # check if food item exists
            try:
                fooditem = FoodItem.objects.get(id=food_id)
                # check if the user has already added that food to cart
                try:
                    # A Cart having a fooditem
                    checkCart = Cart.objects.get(user=request.user, fooditem=fooditem)

                    # increase cart quantity
                    checkCart.quantity += 1
                    checkCart.save()
                    return JsonResponse(
                        {
                            "status": "Success",
                            "message": "increased the cart quantity",
                            "cart_counter": get_cart_counter(request),
                            "quantity": checkCart.quantity,
                            "cart_amount": get_cart_amounts(request),
                        }
                    )
                except:
                    checkCart = Cart.objects.create(
                        user=request.user, fooditem=fooditem, quantity=1
                    )
                    return JsonResponse(
                        {
                            "status": "Success",
                            "message": "Added food to cart",
                            "cart_counter": get_cart_counter(request),
                            "quantity": checkCart.quantity,
                            "cart_amount": get_cart_amounts(request),
                        }
                    )
            except:
                return JsonResponse(
                    {"status": "Failed", "message": "Food does not exist"}
                )
        else:
            return JsonResponse({"status": "Failed", "message": "Invalid request"})

    else:
        return JsonResponse(
            {"status": "login_required", "message": "Please login to continue "}
        )


def decrease_cart(request, food_id):
    if request.user.is_authenticated:
        if request.headers.get("x-requested-with") == "XMLHttpRequest":
            # Check if the food item exists
            try:
                fooditem = FoodItem.objects.get(id=food_id)
                # Check if the user has already added that food to the cart
                try:
                    checkCart = Cart.objects.get(user=request.user, fooditem=fooditem)
                    if checkCart.quantity > 1:
                        # decrease the cart quantity
                        checkCart.quantity -= 1
                        checkCart.save()
                    else:
                        checkCart.delete()
                        checkCart.quantity = 0
                    return JsonResponse(
                        {
                            "status": "Success",
                            "message": "Removed fooditem from cart",
                            "cart_counter": get_cart_counter(request),
                            "quantity": checkCart.quantity,
                            "cart_amount": get_cart_amounts(request),
                        }
                    )
                except:
                    return JsonResponse(
                        {
                            "status": "Failed",
                            "message": "You do not have this item in your cart!",
                        }
                    )
            except:
                return JsonResponse(
                    {"status": "Failed", "message": "This food does not exist!"}
                )
        else:
            return JsonResponse({"status": "Failed", "message": "Invalid request!"})

    else:
        return JsonResponse(
            {"status": "login_required", "message": "Please login to continue"}
        )


@login_required(login_url="login")
def cart(request):
    cart_items = Cart.objects.filter(user=request.user)
    print(cart_items)
    context = {
        "cart_items": cart_items,
    }
    return render(request, "marketplace/cart.html", context)


def delete_cart(request, cart_id):
    if request.user.is_authenticated:
        if request.headers.get("x-requested-with") == "XMLHttpRequest":
            try:
                # Get cart item with specific id for user
                cart_item = Cart.objects.get(user=request.user, id=cart_id)
                if cart_item:
                    cart_item.delete()
                    return JsonResponse(
                        {
                            "status": "Success",
                            "message": "Cart item has been deleted!",
                            "cart_counter": get_cart_counter(request),
                            "cart_amount": get_cart_amounts(request),
                        }
                    )
            except:
                return JsonResponse(
                    {"status": "Failed", "message": "Cart Item does not exist!"}
                )
        else:
            return JsonResponse({"status": "Failed", "message": "Invalid request!"})


def search(request):
    address = request.GET["address"]
    latitude = request.GET["lat"]
    longitude = request.GET["lng"]
    keyword = request.GET["keyword"]
    radius = request.GET["radius"]

    fetch_vendors_by_fooditems = FoodItem.objects.filter(
        food_title__icontains=keyword, is_available=True
    ).values_list("vendor", flat=True)

    if latitude and longitude and radius:
        # Distances will be calculated from this point, which does not have to be projected.
        pnt = GEOSGeometry("POINT(%s %s)" % (longitude, latitude))
        print("inside if")
        vendors = (
            Vendor.objects.filter(
                Q(id__in=fetch_vendors_by_fooditems)
                | Q(
                    vendor_name__icontains=keyword,
                    is_approved=True,
                    user__is_active=True,
                )
                | Q(user_profile__location__distance_lte=(pnt, D(km=radius)))
            )  # adds calculated distance field to each vendor wrt to pnt
            .annotate(distance=Distance("user_profile__location", pnt))
            .order_by("distance")
        )
        # print(vendors[0].distance)
        # add distance as km field
        for vendor in vendors:
            vendor.kms = round(vendor.distance.km, 1)

        # print(vendors[0].kms)
    else:
        vendors = Vendor.objects.filter(
            Q(id__in=fetch_vendors_by_fooditems)
            | Q(
                vendor_name__icontains=keyword,
                is_approved=True,
                user__is_active=True,
            )
        )
    vendor_count = vendors.count()

    context = {
        "vendors": vendors,
        "vendor_count": vendor_count,
        "source_location": address,
    }
    return render(request, "marketplace/listings.html", context)


@login_required(login_url="login")
def checkout(request):
    cart_items = Cart.objects.filter(user=request.user).order_by("created_at")
    cart_count = cart_items.count()
    if cart_count <= 0:
        return redirect("market:marketplace")

    user_profile = UserProfile.objects.get(user=request.user)
    default_values = {
        "first_name": request.user.first_name,
        "last_name": request.user.last_name,
        "phone": request.user.phone_number,
        "email": request.user.email,
        "address": user_profile.address,
        "country": user_profile.country,
        "state": user_profile.state,
        "city": user_profile.city,
        "pin_code": user_profile.pin_code,
    }
    form = OrderForm(initial=default_values)
    print(cart_items)
    context = {
        "form": form,
        "cart_items": cart_items,
    }

templates/marketplace/cart.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
 		<!-- Main Section Start -->
     <div class="main-section pt-5">

      <div class="page-section">
        <div class="container ">
          <div class="row">
          
            <!-- 1st col-->
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">

              <div class="tabs-holder horizontal">
                <ul class="stickynav-tabs nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#home"><i class="fa fa-shopping-cart text-danger"></i>Menu</a></li>
                  
                </ul>

                <div class="tab-content">
                  <div id="home" class="tab-pane in active">
                    <div class="menu-itam-holder">
                      
                      <div id="menu-item-list-6272" class="menu-itam-list">

                        <div id="empty-cart" class="text-center p-5" style="display:none">
                          <h3>Cart is empty</h3>
                        </div>  
                        
                     <ul> 
                       {% if cart_items %}
                        
                          {% for item in cart_items %}
                  
                          <li id="cart-item-{{item.pk}}">
                            <div class="image-holder"><img src="{{item.fooditem.image.url}}" alt=""></a></div>
                            <div class="text-holder">
                              <h6>{{item.fooditem.food_title}}</h6>
                              <span>{{item.fooditem.description}}</span>
                              <a href="{% url 'market:vendor_detail' item.fooditem.vendor.vendor_slug %}" class="badge badge-primary">{{item.fooditem.vendor}}</a>
                              
                            </div>
                            <div class="price-holder">
                              <span class="price">{{item.fooditem.price}}</span>

                              <a href="#" class="decrease_cart" style="margin-right:28px;" data-id="{{item.fooditem.pk}}" id="{{item.pk}}" data-url="{% url 'market:decrease_cart' item.fooditem.pk %}" ><i class="icon-minus text-danger"></i></a>
                                <label id="qty-{{item.fooditem.pk}}">0</label>
                              <a href="#" class="add_to_cart" data-id="{{item.fooditem.pk}}" data-url="{% url 'market:add_to_cart' item.fooditem.pk %}"><i class="icon-plus4 text-success"></i></a>
                              <a href="#" class="delete_cart" data-id="{{item.pk}}" data-url="{% url 'market:delete_cart' item.pk %}"><i class="icon-bin text-danger"></i></a>
                            </div>
                          </li>
                          {% endfor %}
                          
                        {% else %}
                          <div class="text-center p-5">
                            <h3>Cart is empty</h3>
                          </div>  
                        {% endif %}  
                    </ul>
                    
                        
                      </div>
                      {% for item in cart_items %}
                        <span id="qty-{{item.fooditem.id}}" class="item_qty" data-qty={{item.quantity}}></span>
                      {% endfor %}

                    </div>
                  </div>
                  
                </div>
              </div>
            </div>

            <!-- 2nd col-->
            <!-- Your order section -->
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                  <div class="tabs-holder horizontal">
                      <ul class="stickynav-tabs nav nav-tabs">
                          <li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Your Order</a></li>
                          
                      </ul>
                      <div class="tab-content">
                          <div id="home" class="tab-pane in active">
                              <div class="menu-itam-holder">
                                  
                                  <div>
                                      <ul>
                                          <li style="list-style-type: none;">
                                              Subtotal
                                              <span class="price float-right">
                                                  <span class="currency">$</span>
                                                  <span id="subtotal">{{subtotal}}</span>
                                              </span>
                                          </li>

                                          <!--Display tax  -->
                                          {% for key,value in tax_dict.items %}
                                              {% for percent,amt in value.items %}
                                                  <li style="list-style-type: none; font-weight: 600;">
                                                    {{key}} <small>( {{percent}} % )</small>
                                                    <span class="price float-right">
                                                      <span class="currency">$</span>
                                                      <span id="tax-{{key}}">{{amt}}</span>
                                                    </span>
                                                  </li>
                                              {% endfor %}
                                            {% endfor %}

                                          <li style="list-style-type: none; font-weight: 600;">
                                               Total
                                              <span class="price float-right">
                                                  <span class="currency">$</span>
                                                  <span id="total">{{grand_total}}</span>
                                              </span>
                                          </li>
                                          <a href="{% url 'checkout' %}" class="btn btn-danger w-100 p-2 mt-3">Proceed To Checkout</a>
                                      </ul>
                                  </div>
                                  
                              </div>
                          </div>
                          
                      </div>
                  </div>
              </div>    
            
            </div>
        </div>
      </div>
    </div>
    <!-- Main Section End -->
{% endblock %}

templates/marketplace/checkout.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
 		<!-- Main Section Start -->
     <div class="main-section pt-5">

      <div class="page-section">
        <div class="container ">
          <div class="row">
          
            <!-- 1st col Billing address section-->
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

              <div class="tabs-holder horizontal">
                <ul class="stickynav-tabs nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#home"><i class="fa fa-shopping-cart text-danger"></i>Billing address</a></li>
                </ul>

                <div class="tab-content">
                  <div id="home" class="tab-pane in active">
                    <div class="menu-itam-holder">
                      <div id="menu-item-list-6272" class="menu-itam-list">
                        <!-- Form-->
                        <form action="{% url 'order:place_order' %}" method="POST">
                          {% csrf_token %}

                          <div class="row">
                              <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                  First Name: {{ form.first_name }}
                              </div>
                              <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                  Last Name: {{ form.last_name }}
                              </div>
                          </div>

                          <div class="row">
                              <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                  Phone Number: {{ form.phone }}
                              </div>
                              <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                  Email Address: {{ form.email }}
                              </div>
                          </div>

                          <div class="row">
                              <div class="form-group col-md-12 col-sm-12 col-lg-12">
                                  Address: {{ form.address }}
                              </div>
                          </div>

                          <div class="row">
                              <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                  Country: {{ form.country }}
                              </div>
                              <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                  State: {{ form.state }}
                              </div>
                          </div>

                          <div class="row">
                              <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                  City: {{ form.city }}
                              </div>
                              <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                  Pin Code: {{ form.pin_code }}
                              </div>
                          </div>

                      </div>

                     
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>

            <!-- 2nd col-->
            <!-- payment method section -->
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                  <div class="tabs-holder horizontal">
                      <ul class="stickynav-tabs nav nav-tabs">
                          <li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Payment Method</a></li> 
                      </ul>
                      <div class="tab-content">
                          <div id="home" class="tab-pane in active">
                              <div class="menu-itam-holder">
                                  
                                <!--Display cart items -->
                                <div id="menu-item-list-6272" class="menu-itam-list">      
                                  <ul> 
                                    {% if cart_items %}
                                       {% for item in cart_items %}
                               
                                       <li id="cart-item-{{item.pk}}">
                                         <div class="image-holder"><img src="{{item.fooditem.image.url}}" alt=""></a></div>
                                         <div class="text-holder">
                                           <h6>{{item.fooditem.food_title}}</h6>
                                           <span>{{item.fooditem.description}}</span>
                                           <a href="{% url 'market:vendor_detail' item.fooditem.vendor.vendor_slug %}" class="badge badge-primary">{{item.fooditem.vendor}}</a>
                                           
                                         </div>
                                         <div class="price-holder">
                                          <div class="quantity" style="display: inline-block; margin-right: 10px;">
                                            <span>{{ item.quantity }} QTY</span>
                                          </div>
                                           <span class="price">{{item.fooditem.price}}</span>
                                            
                                         </div>
                                       </li>
                                       {% endfor %}
                                       
                                     {% else %}
                                       <div class="text-center p-5">
                                         <h3>Cart is empty</h3>
                                       </div>  
                                     {% endif %}  
                                 </ul>
                                </div>  
                                 <!--END Display cart items -->
                                <!--total cost and payment method -->
                              
                                  <ul>
                                      <li style="list-style-type: none;">
                                          Subtotal
                                          <span class="price float-right">
                                              <span class="currency">$</span>
                                              <span id="subtotal">{{subtotal}}</span>
                                          </span>
                                      </li>

                                      <!--Display tax  -->
                                      {% for key,value in tax_dict.items %}
                                          {% for percent,amt in value.items %}
                                              <li style="list-style-type: none; font-weight: 600;">
                                                {{key}} <small>( {{percent}} % )</small>
                                                <span class="price float-right">
                                                  <span class="currency">$</span>
                                                  <span id="tax-{{key}}">{{amt}}</span>
                                                </span>
                                              </li>
                                          {% endfor %}
                                        {% endfor %}

                                      <li style="list-style-type: none; font-weight: 600;">
                                           Total
                                          <span class="price float-right">
                                              <span class="currency">$</span>
                                              <span id="total">{{grand_total}}</span>
                                          </span>
                                      </li>
                                      <!-- Select Payment Method-->
                                      <div class="payment-method">
                                        <label>
                                          <input type="radio" name="payment_method" value="PayPal">
                                          <img src="{% static 'images/PayPal.png' %}" alt="Paypal" width="100">
                                        </label>
                                        <label>
                                          <input type="radio" name="payment_method" value="RazorPay">
                                          <img src="{% static 'images/razorpay_logo.png' %}" alt="RazorPay" width="100">
                                        </label>
                                      </div> 
                                      <span class="text-danger" id="payment-method-error"></span>
                                      <button onclick="return paymentMethodConfirm()" type="submit" class="btn btn-danger w-100 p-2 mt-3">PLACE ORDER</button>
                                  </ul>
                           
                                <!-- end cost and payment-->
                            </div>
                          </div>
                          
                      </div>
                  </div>
              </div>    
            
            </div>
            
          </form>
        </div>
      </div>
    </div>
    <!-- Main Section End -->
    <script>
       function paymentMethodConfirm(){
         var paymentMethod=$("input[name='payment_method']:checked").val()
        // console.log(paymentMethod)
         if(!paymentMethod){
          $('#payment-method-error').html("Select Payment method");
          return false;
         }else{
            var conf=confirm('You have selected'+paymentMethod+' as your preferred payment method. \n Click "OK" to continue . ')
           // console.log(conf)
            if(conf==true){
              return true;
            }else{
              return false;
            }
         }
       }
       //remove error when user selects payment method
      $('input[name=payment_method]').on('change',function(){
         $('#payment-method-error').html("")
      })

    </script>
{% endblock %}