accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.myAccount),
    path("registerUser/", views.registerUser, name="registerUser"),
    path("registerVendor/", views.registerVendor, name="registerVendor"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("myAccount/", views.myAccount, name="myAccount"),
    path("custDashboard/", views.custDashboard, name="custDashboard"),
    path("vendorDashboard/", views.vendorDashboard, name="vendorDashboard"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path(
        "reset_password_validate/<uidb64>/<token>/",
        views.reset_password_validate,
        name="reset_password_validate",
    ),
    path("reset_password/", views.reset_password, name="reset_password"),
    path("vendor/", include("vendor.urls", namespace="vendor")),
    path("customer/", include("customers.urls", namespace="customer")),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("accounts.urls", namespace="accounts")),
    path("marketplace/", include("marketplace.urls", namespace="market")),
    path("checkout/", MarketplaceViews.checkout, name="checkout"),
    path("order/", include("orders.urls", namespace="order")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home")
    ]

marketplace/urls.py
from django.urls import path
from . import views

app_name = "market"

urlpatterns = [
    path("", views.marketplace, name="marketplace"),
    path("<slug:vendor_slug>/", views.vendor_detail, name="vendor_detail"),
    # Add to Cart
    path("add_to_cart/<int:food_id>/", views.add_to_cart, name="add_to_cart"),
    path("decrease_cart/<int:food_id>/", views.decrease_cart, name="decrease_cart"),
    # show cart Items
    path("show/cart", views.cart, name="cart"),
    path("show/search", views.search, name="search"),
    # DELETE CART ITEM
    path("delete_cart/<int:cart_id>/", views.delete_cart, name="delete_cart"),
]

templates/includes/alerts.html
{% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{message.tags}} " role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
   <strong>{{message}}</strong>
  </div>
  {% endfor %}
{% endif %}

templates/includes/c_sidebar.html
<div class="user-account-nav user-account-sidebar">
  <div class="user-nav-list">
    <ul>
      <li class="{% if 'custDashboard' in request.path %}active{% endif %}"><a href="{% url 'accounts:custDashboard' %}"><i class="icon-dashboard3"></i>Dashboard</a></li>
      <li><a href="restaurant-orders.html"><i class="icon-add_shopping_cart"></i> My Orders</a></li>
      <li class="{% if 'profile' in request.path %}active{% endif %}"><a href="{% url 'accounts:customer:cprofile' %}"><i class="icon-unlock-alt"></i>Profile Setting</a></li>
      <li><a class="logout-btn" href="registration.html"><i class="icon-log-out"></i>Signout</a></li>
    </ul>
  </div>
</div>

templates/includes/cover.html
{% load static %}

<div class="page-section restaurant-detail-image-section" style=" background: url({% if vendor.user_profile.cover_photo %}{{vendor.user_profile.cover_photo.url}}{% else %}{% static 'images/default-cover.png' %}{% endif %}) no-repeat scroll 0 0 / cover;">
  <!-- Container Start -->
  <div class="container">
    <!-- Row Start -->
    <div class="row">
      <!-- Column Start -->
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="company-info-detail">
          <div class="company-info">
            <div class="img-holder">
              <figure>
                {% if vendor.user_profile.profile_picture %}
                  <img src="{{ vendor.user_profile.profile_picture.url}}" alt="">
                {% else %}
                  <img src="{% static 'images/default-profile.png' %}" alt="">
                {% endif %}
              </figure>
            </div>

            <div class="text-holder">
              <span class="restaurant-title"> {{vendor.vendor_name}}</span>
              <div class="text">
                <i class="icon-location"></i>
                {% if vendor.user_profile.address %}
                   <p>{{vendor.user_profile.address}}</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Column End -->
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</div>

templates/includes/footer.html
{% load static %}
    <!-- Footer Start -->
		<footer id="footer" class="footer-style-2">
			<div class="footer-widget">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="widget widget-newsletter">
								<div class="widget-title">
									<h5>Subscribe to our Newsletter</h5>
								</div>
								<div class="fieldset">
									<form action="#">
										<div class="field-holder">
											<label>
												<i class=" icon-envelope3"></i>
												<input type="text" class="field-input" placeholder=" Enter Your Email Address...">
											</label>
										</div>
										<div class="field-holder btn-holder">
											<input class="subscribe-btn bgcolor" type="submit" value="Sign Up">
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copyright-sec">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="copyright-inner">
								<div class="copy-right">
									<p>© 2023 Foodbakery. All Rights Reserved. Developed By <a href="#">Irshad Khan</a>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- /.cs-copyright -->
		</footer>
		<!-- Footer End -->

	<!-- Modal Popup End -->
	<script src="{% static 'js/scripts.js' %}"></script>
	<script src="{% static 'js/functions.js' %}"></script>    

templates/includes/header.html
{% load static %}
  <!-- Header Start -->
  <header id="header">
    <div class="main-header">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="logo">
              <figure>
                <a href="{% url 'main:home' %}" class="light-logo">
                  <img src="{% static 'logo/foodOnlineLogo.png' %}" alt="Foodonline" width="200">
                </a>
              </figure>
            </div>
        
            <div class="main-location">
              <ul>
                <li class="location-has-children choose-location">
                  <form action="#">
                    <input type="text" value="" name="location" id="location" placeholder="Your current  location" autocomplete="off">
                    <span id="foodbakery_radius_location_open" class="foodbakery-radius-location" onclick="getLocation()"><i class="icon-target5"></i></span>
                  </form>
                  
                </li>
              </ul>
              </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="login-option">
              <!--Cart-->
              {% if user.is_authenticated %}
              <a href="{% url 'market:cart' %}">
                  <i class="fa fa-shopping-cart text-danger" style="font-size: 20px;"></i>
                  <span class="badge badge-warning" id="cart_counter" style="border-radius: 50px; position: relative; bottom:10px; left: -5px;">{{ cart_count }}</span>
              </a>
              {% endif %}

              <!-- login options-->
              <a class="btn btn-outline-primary text-uppercase font-weight-bold" href="{% url 'market:marketplace' %}">marketplace</a>
            
              {% if user.is_authenticated %}
                <a class="cs-color cs-popup-joinus-btn login-popup text-primary" href="{% url 'accounts:myAccount' %}">Dashboard</a>

                <a class="cs-color cs-popup-joinus-btn login-popup text-danger" href="{% url 'accounts:logout' %}">Logout</a>
              {% else %}
                <a class="cs-color cs-popup-joinus-btn login-popup" href="{% url 'accounts:login' %}">Login</a>
                <a class="cs-color cs-popup-joinus-btn login-popup" href="{% url 'accounts:registerUser' %}">Register</a>
                <a class="get-start-btn" href="{% url 'accounts:registerVendor' %}">
                Register
                Restaurant </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- Header End -->

  <script>
    var x = document.getElementById("location");
    var cur_location=sessionStorage.getItem("cur_location")
    if(cur_location){
      x.value=cur_location
    }
 
    function getLocation() {
        if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
        } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }
    
    function showPosition(position) {
      console.log(position)
        var lat = position.coords.latitude
        var lng = position.coords.longitude

        //send lat lng to googlemaps api to get address
        var GOOGLE_API_KEY="{{GOOGLE_API_KEY}}"
        var url="https://maps.googleapis.com/maps/api/geocode/json?latlng="+lat+","+lng+"+&key="+GOOGLE_API_KEY;


        $.ajax({
          url:url,
          type:"GET",
          success:function(response){
  
            var cur_location=response.results[0].formatted_address
            x.value=cur_location
            sessionStorage.setItem("cur_location",cur_location)
            window.location="?lat="+lat+"&lng="+lng
          }
        })
    }
    </script>

templates/includes/v_sidebar.html
<div class="user-account-nav user-account-sidebar">
  <div class="user-nav-list">
    <ul>
      <li class="{% if 'vendorDashboard' in request.path %}active{% endif %}"><a href="{% url 'accounts:vendorDashboard' %}"><i class="icon-dashboard3"></i>Dashboard</a></li>
      <li class="{% if 'vendor/profile' in request.path %}active{% endif %}"><a href="{% url 'accounts:vendor:vprofile' %}"><i class="icon-building"></i>My Restaurant </a></li>
      <li class="{% if 'vendor/menu-builder' in request.path %}active{% endif %}"><a href=" {% url 'accounts:vendor:menu_builder' %}"><i class="icon-menu5"></i>Menu Builder</a></li>
      <li class="{% if 'opening-hours' in request.path %}active{% endif %}"><a href=" {% url 'accounts:vendor:opening_hours' %}"><i class="icon-clock"></i>Opening Hours</a></li>
      <li><a href="restaurant-orders.html"><i class="icon-add_shopping_cart"></i>Orders</a></li>
      <li><a href="restaurant-earnings.html"><i class="icon-money"></i>Earnings</a></li>
      <li><a href="restaurant-statement.html"><i class="icon-file-text22"></i>Statement</a></li>
      <li><a href="restaurant-change-password.html"><i class="icon-unlock-alt"></i>Change Password</a></li>
      <li><a class="logout-btn" href="registration.html"><i class="icon-log-out"></i>Signout</a></li>
    </ul>
  </div>
</div>