config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("accounts.urls", namespace="accounts")),
    path("marketplace/", include("marketplace.urls", namespace="market")),
    path("checkout/", MarketplaceViews.checkout, name="checkout"),
    path("order/", include("orders.urls", namespace="order")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home")
    ]

marketplace/urls.py
from django.urls import path
from . import views

app_name = "market"

urlpatterns = [
    path("", views.marketplace, name="marketplace"),
    path("<slug:vendor_slug>/", views.vendor_detail, name="vendor_detail"),
    # Add to Cart
    path("add_to_cart/<int:food_id>/", views.add_to_cart, name="add_to_cart"),
    path("decrease_cart/<int:food_id>/", views.decrease_cart, name="decrease_cart"),
    # show cart Items
    path("show/cart", views.cart, name="cart"),
    path("show/search", views.search, name="search"),
    # DELETE CART ITEM
    path("delete_cart/<int:cart_id>/", views.delete_cart, name="delete_cart"),
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = "order"

urlpatterns = [
    path("place_order/", views.place_order, name="place_order"),
    path("payments/", views.payments, name="payments"),
    path("order_complete/", views.order_complete, name="order_complete"),
]

orders/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem


class Payment(models.Model):
    PAYMENT_METHOD = (
        ("PayPal", "PayPal"),
        ("RazorPay", "RazorPay"),  # add others for more methods
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id


class Order(models.Model):
    STATUS = (
        ("New", "New"),
        ("Accepted", "Accepted"),
        ("Completed", "Completed"),
        ("Cancelled", "Cancelled"),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, blank=True, null=True
    )
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(
        blank=True,
        help_text="Data format: {'tax_type':{'tax_percentage':'tax_amount'}}",
    )
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15, choices=STATUS, default="New")
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Concatenate first name and last name
    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.order_number


class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, blank=True, null=True
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fooditem.food_title

orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "first_name",
            "last_name",
            "phone",
            "email",
            "address",
            "country",
            "state",
            "city",
            "pin_code",
        ]

orders/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from accounts.utils import send_notification
from marketplace.models import Cart
from marketplace.context_processors import get_cart_amounts
from .forms import OrderForm
from .models import Order, OrderedFood, Payment
import simplejson as json
from .utils import generateOrderNumber
from django.contrib.auth.decorators import login_required
from config import settings
import razorpay

client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))


# Create your views here.
@login_required(login_url="login")
def place_order(request):
    cart_items = Cart.objects.filter(user=request.user).order_by("created_at")
    cart_count = cart_items.count()
    if cart_count <= 0:
        return redirect("market:marketplace")
    cart_details = get_cart_amounts(request)
    # print(cart_details)
    # print("::::", request.POST)
    subtotal = cart_details["subtotal"]
    total_tax = cart_details["tax"]
    grand_total = cart_details["grand_total"]
    tax_data = cart_details["tax_dict"]
    # print(subtotal, tax_data, grand_total, total_tax)

    if request.method == "POST":
        # pass post data to orderForm
        form = OrderForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            # create Order instance and fill values
            order = Order()
            order.first_name = form.cleaned_data["first_name"]
            order.last_name = form.cleaned_data["last_name"]
            order.phone = form.cleaned_data["phone"]
            order.email = form.cleaned_data["email"]
            order.address = form.cleaned_data["address"]
            order.country = form.cleaned_data["country"]
            order.state = form.cleaned_data["state"]
            order.city = form.cleaned_data["city"]
            order.pin_code = form.cleaned_data["pin_code"]
            order.user = request.user
            order.total = grand_total
            order.tax_data = json.dumps(tax_data)
            order.total_tax = total_tax
            order.payment_method = request.POST["payment_method"]
            order.save()  # order id/ pk is generated
            order.order_number = generateOrderNumber(order.pk)
            order.save()
            # print(order)
            # Razorpay payments
            DATA = {
                "amount": float(order.total) * 100,  # since order is in paise
                "currency": "INR",
                "receipt": "receipt" + order.order_number,
            }
            RazorPayOrder = client.order.create(data=DATA)
            print(RazorPayOrder)
            razorpay_order_id = RazorPayOrder["id"]
            context = {
                "order": order,
                "cart_items": cart_items,
                "razorpay_order_id": razorpay_order_id,
                "razorpay_key_id": settings.RAZORPAY_KEY_ID,
                "razorpay_amount": float(order.total) * 100,
            }

            return render(request, "orders/place_order.html", context)
    return render(request, "orders/place_order.html")


@login_required(login_url="login")
def payments(request):
    # Check if the request is ajax or not
    if (
        request.headers.get("x-requested-with") == "XMLHttpRequest"
        and request.method == "POST"
    ):
        # STORE THE PAYMENT DETAILS IN THE PAYMENT MODEL
        order_number = request.POST.get("order_number")
        transaction_id = request.POST.get("transaction_id")
        payment_method = request.POST.get("payment_method")
        status = request.POST.get("status")

        order = Order.objects.get(user=request.user, order_number=order_number)
        payment = Payment(
            user=request.user,
            transaction_id=transaction_id,
            payment_method=payment_method,
            amount=order.total,
            status=status,
        )
        payment.save()

        # UPDATE THE ORDER MODEL
        order.payment = payment
        order.is_ordered = True
        order.save()

        # move cart item to ordered food model
        cart_items = Cart.objects.filter(user=request.user)
        for item in cart_items:
            ordered_food = OrderedFood()
            ordered_food.order = order
            ordered_food.payment = payment
            ordered_food.user = request.user
            ordered_food.fooditem = item.fooditem
            ordered_food.quantity = item.quantity
            ordered_food.price = item.fooditem.price
            ordered_food.amount = item.fooditem.price * item.quantity
            ordered_food.save()

        # SEND EMAIL TO THE CUSTOMER
        mail_subject = "Thank you for ordering with us."
        mail_template = "orders/order_confirmation_email.html"
        context = {
            "user": request.user,
            "order": order,
            "to_email": order.email,
        }
        send_notification(mail_subject, mail_template, context)

        # SEND ORDER RECEIVED EMAIL TO VENDORS
        mail_subject = "You have received a new order."
        mail_template = "orders/new_order_received.html."
        to_emails = []
        for i in cart_items:
            # only for unique emails send mail
            if i.fooditem.vendor.user.email not in to_emails:
                # add email in to_email to skip him if multiple fooditems is there with same vendor.
                to_emails.append(i.fooditem.vendor.user.email)

                context = {
                    "user": i.fooditem.vendor.user,
                    "order": order,
                    "to_email": i.fooditem.vendor.user.email,
                }
                send_notification(mail_subject, mail_template, context)

        # CLEAR THE CART IF THE PAYMENT IS SUCCESS
        cart_items.delete()
        response = {
            "order_number": order_number,
            "transaction_id": transaction_id,
        }
        return JsonResponse(response)

    return HttpResponse("data saved and mail sent")


def order_complete(request):
    order_number = request.GET.get("order_no")
    transaction_id = request.GET.get("trans_id")

    try:
        order = Order.objects.get(
            order_number=order_number,
            payment__transaction_id=transaction_id,
            is_ordered=True,
        )
        ordered_food = OrderedFood.objects.filter(order=order)

        subtotal = 0
        for item in ordered_food:
            subtotal += item.price * item.quantity

        tax_data = json.loads(order.tax_data)
        print(tax_data)
        context = {
            "order": order,
            "ordered_food": ordered_food,
            "subtotal": subtotal,
            "tax_data": tax_data,
        }
        return render(request, "orders/order_complete.html", context)
    except:
        return redirect("main:home")

templates/orders/new_order_received.html
{% autoescape off %}

Hi {{user}},

Yot have received an order.
Your order number:{{order.order_number}}
Your transaction id :{{order.payment.transaction_id}}

{% endautoescape %}

templates/orders/order_complete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5 mb-5">
    <div class="justify-content-center row">
        <div class="col-md-8">
            <div class="bg-white p-3">
                <img src="{% static 'logo/foodOnlineLogo.png' %}" alt="foodOnline Logo" width="300">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="mt-2 mb-3">Thank you for your order.</h4>
                    </div>
                    <div class="col-md-6 text-right">
                        <p class="mb-0">{{ order.name }}</p>
                        <p class="mb-0">{{ order.address }}</p>
                        <p class="mb-0">{{ order.phone }}</p>
                        <p class="mb-0">{{ order.email }}</p>
                    </div>
                </div>
                
                <h6>Hello {{ order.name }}, </h6><span>Review your order details below.</span>
                <hr>

                <div class="d-flex justify-content-between">
                    <div>
                        <span class="d-block">Order Date: </span><span class="font-weight-bold">{{ order.created_at }}</span>
                    </div>
                    <div>
                        <span class="d-block">Order No: </span><span class="font-weight-bold">{{ order.order_number }}</span>
                    </div>
                    <div>
                        <span class="d-block">Payment Method: </span><span class="font-weight-bold">{{ order.payment_method }}</span>
                    </div>
                    <div>
                        <span class="d-block">Transaction ID: </span><span class="font-weight-bold">{{ order.payment.transaction_id }}</span>
                    </div>
                </div>
                <hr>
                <table class="table">
                    <tbody>
                        {% for item in ordered_food %}
                        <tr>
                            <td><img src="{{ item.fooditem.image.url }}" width="60" alt="Food Image"></td>
                            <td>
                                <p class="mb-0"><b>{{ item.fooditem }}</b></p>
                                <a class="text-muted" href="{% url 'market:vendor_detail' item.fooditem.vendor.vendor_slug %}">{{ item.fooditem.vendor.vendor_name }}</a>
                            </td>
                            <td>{{ item.quantity }} QTY</td>
                            <td>${{ item.fooditem.price }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="row mt-5">
                    <div class="d-flex justify-content-center col-md-6">
                        <img src="{% static 'images/paid.png' %}" width="200">
                    </div>
                    <div class="col-md-6">
                        <ul>
                            <li style="list-style-type: none;">
                                Subtotal
                                <span class="price float-right">
                                    <span class="currency">$</span>
                                    <span id="subtotal">{{ subtotal }}</span>
                                </span>
                            </li>

                             <!--Display tax  -->
                          {% for key,value in tax_data.items %}
                             {% for percent,amt in value.items %}
                                 <li style="list-style-type: none; font-weight: 600;">
                                   {{key}} <small>( {{percent}} % )</small>
                                   <span class="price float-right">
                                     <span class="currency">$</span>
                                     <span id="tax-{{key}}">{{amt}}</span>
                                   </span>
                                 </li>
                             {% endfor %}
                           {% endfor %}  


                            <li style="list-style-type: none; font-weight: 600;">
                                TOTAL
                                <span class="price float-right">
                                    <span class="currency">$</span>
                                    <span id="total">{{ order.total }}</span>
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
                <hr>
                <div class="d-flex justify-content-between">
                    <div>
                        <span class="d-block font-weight-bold">Thanks for ordering with us.</span>
                        <span>FoodOnline Team</span>
                    </div>
                    <div class="d-flex justify-content-end align-items-end">
                        <span class="d-block font-weight-bold">Need help?</span>
                        <span>Call - +91 123234232</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/orders/order_confirmation_email.html
{% autoescape off %}

Hi {{user}},

Thank you for your order.
Your order number:{{order.order_number}}
Your transaction id :{{order.payment.transaction_id}}

{% endautoescape %}

templates/orders/place_order.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
 		<!-- Main Section Start -->
     <div class="main-section pt-5">

      <div class="page-section">
        <div class="container ">
          <div class="row">
          
            <!-- 1st col Billing address section-->
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

              <div class="tabs-holder horizontal">
                <ul class="stickynav-tabs nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#home"><i class="fa fa-shopping-cart text-danger"></i>Billing address</a></li>
                </ul>

                <div class="tab-content">
                  <div id="home" class="tab-pane in active">
                    <div class="menu-itam-holder">
                      <div id="menu-item-list-6272" class="menu-itam-list">
                        <!-- Address-->
                        <div class="billing-address">
                          <div><b>{{ order.name }}</b></div>
                          <div>{{ order.address }}</div>
                          <div>{{ order.city }} - {{ order.pin_code }}</div>
                          <div>{{ order.state }}, {{ order.country }}</div>
                          <div><b>Phone: </b>{{ order.phone }}</div>
                          <div><b>Email: </b>{{ order.email }}</div>
                          <div><b>Payment: </b>{{ order.payment_method }}</div>
                          <br>
                          <div><a href="{% url 'checkout' %}" class="btn btn-outline-danger">Edit</a></div>
                          <br>

                      </div>
                      
                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>

            <!-- 2nd col-->
            <!-- payment method section -->
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                  <div class="tabs-holder horizontal">
                      <ul class="stickynav-tabs nav nav-tabs">
                          <li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Payment Method</a></li> 
                      </ul>
                      <div class="tab-content">
                          <div id="home" class="tab-pane in active">
                              <div class="menu-itam-holder">
                                  
                                <!--Display cart items -->
                                 <div id="menu-item-list-6272" class="menu-itam-list">      
                                  <ul> 
                                    {% if cart_items %}
                                       {% for item in cart_items %}
                               
                                       <li id="cart-item-{{item.pk}}">
                                         <div class="image-holder"><img src="{{item.fooditem.image.url}}" alt=""></a></div>
                                         <div class="text-holder">
                                           <h6>{{item.fooditem.food_title}}</h6>
                                           <span>{{item.fooditem.description}}</span>
                                           <a href="{% url 'market:vendor_detail' item.fooditem.vendor.vendor_slug %}" class="badge badge-primary">{{item.fooditem.vendor}}</a>
                                           
                                         </div>
                                         <div class="price-holder">
                                          <div class="quantity" style="display: inline-block; margin-right: 10px;">
                                            <span>{{ item.quantity }} QTY</span>
                                          </div>
                                           <span class="price">{{item.fooditem.price}}</span>
                                            
                                         </div>
                                       </li>
                                       {% endfor %}
                                       
                                     {% else %}
                                       <div class="text-center p-5">
                                         <h3>Cart is empty</h3>
                                       </div>  
                                     {% endif %}  
                                 </ul>
                                </div>  
                                 <!--END Display cart items -->
                                <!--total cost and payment method -->
                              
                                  <ul>
                                      <li style="list-style-type: none;">
                                          Subtotal
                                          <span class="price float-right">
                                              <span class="currency">$</span>
                                              <span id="subtotal">{{subtotal}}</span>
                                          </span>
                                      </li>

                                      <!--Display tax  -->
                                      {% for key,value in tax_dict.items %}
                                          {% for percent,amt in value.items %}
                                              <li style="list-style-type: none; font-weight: 600;">
                                                {{key}} <small>( {{percent}} % )</small>
                                                <span class="price float-right">
                                                  <span class="currency">$</span>
                                                  <span id="tax-{{key}}">{{amt}}</span>
                                                </span>
                                              </li>
                                          {% endfor %}
                                        {% endfor %}

                                      <li style="list-style-type: none; font-weight: 600;">
                                           Total
                                          <span class="price float-right">
                                              <span class="currency">$</span>
                                              <span id="total">{{grand_total}}</span>
                                          </span>
                                      </li>
                                      <!-- Select Payment Method-->
                                      {% if order.payment_method == 'PayPal' %}
                                        <div id="paypal-button-container"></div>
                                      {% elif order.payment_method == 'RazorPay' %}
                                        <div id="rzp_payment_button">
                                          <button class="btn btn-danger w-100 p-2" id="rzp-button1">Pay with RazorPay</button>
                                          <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
                                        </div>
                                      {% endif %}
                                  
                                  </ul>
                           
                                <!-- end cost and payment-->
                            </div>
                          </div>
                          
                      </div>
                  </div>
              </div>    
            
            </div>
            
          </form>
        </div>
      </div>
    </div>
    <!-- Main Section End -->
    <script>

      // using jQuery
function getCookie(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie != '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
          var cookie = jQuery.trim(cookies[i]);
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) == (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
          }
      }
  }
  return cookieValue;
}
      var csrftoken = getCookie('csrftoken');
      var grand_total= '{{grand_total}}'
      var payment_url="{% url 'order:payments' %}"
      var order_complete_url="{% url 'order:order_complete' %}"
      var order_number={{order.order_number}}
       // Render the PayPal button into #paypal-button-container
      //console.log(payment_url,order_number,csrftoken)
    paypal.Buttons({

      // Set up the transaction
      createOrder: function(data, actions) {
          return actions.order.create({
              purchase_units: [{
                  amount: {
                      value: grand_total
                  }
              }]
          });
      },

      // Finalize the transaction
      onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {
              // Successful capture! For demo purposes:
              console.log(orderData)
              var transaction = orderData.purchase_units[0].payments.captures[0];
              var transaction_id=transaction.id
              var status=orderData.status
              var payment_method="PayPal"
              console.log(transaction_id,status)

              sendTransaction(transaction_id,status,payment_method)
          
          });
      }

  }).render('#paypal-button-container');

  //razorpay payment section 
var options = {
  "key": "{{razorpay_key_id}}", // Enter the Key ID generated from the Dashboard
  "amount": "{{razorpay_amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
  "currency": "INR",
  "name": "foodOnline", //your business name
  "description": "Complete your payment",
  "image": "{% static 'logo/foodOnlineLogo.png' %}",
  "order_id": "{{razorpay_order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
  "handler": function (response){
      console.log(response)
      var transaction_id=response.razorpay_payment_id
      var status="Success"
      var payment_method="RazorPay"

      sendTransaction(transaction_id,status,payment_method)

  },
  "prefill": { //We recommend using the prefill parameter to auto-fill customer's contact information, especially their phone number
     "name": "{{order.name}}",//your customer's name
     "email": "{{order.email}}",
     "contact": "{{order.phone}}"//Provide the customer's phone number for better conversion rates 
  },
  "notes": {
      "address": "Razorpay Corporate Office"
  },
  "theme": {
      "color": "#3399cc"
  }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
      alert(response.error.code);
      alert(response.error.description);
      alert(response.error.source);
      alert(response.error.step);
      alert(response.error.reason);
      alert(response.error.metadata.order_id);
      alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
  rzp1.open();
  e.preventDefault();
}

  //send data to payment view to store in db
  function sendTransaction(transaction_id,status,payment_method){
      $.ajax({
        type:'POST',
        url:payment_url,
        data:{
          'order_number':order_number,
          'transaction_id':transaction_id,
          'payment_method':payment_method,
          'status':status,
          'csrfmiddlewaretoken':csrftoken
        },
        success:function(response){
          console.log(response)
          window.location.href=order_complete_url+'?order_no='+response.order_number+'&trans_id='+response.transaction_id
        }
      })
  }

    </script>
{% endblock %}